### PR TITLE
Rename QtcCppcheck -> Cppcheck

### PR DESCRIPTION
**Pull request by orgads**
Just a proposal. None of Qtc plugins (at least the built in ones) has this prefix...

### CODE REVIEW

**Comment by OneMoreGres** [comment]
Hi! At first, thanks for all these PRs.
About this one: i don't think that plugin's name matters a lot, but changing it might cause some inconvenience in installing/upgrading/scripting. So i'll keep the old one for now.

**Comment by orgads** [comment]
How about changing it, but keeping the library target file name only? I'll try that.

**Comment by OneMoreGres** [comment]
AFAIK Qtc identifies plugin by its name, so it would treat renamed as new one. And "wrong" file's name with "correct" plugin's name (and visa versa) doesn't sound better then "wrong" names everywhere :)
So, although the renaming idea is right i general, i don't think it's worth making it.

**Comment by orgads** [comment]
It works fine here. Qtc uses the json file for the name, the file name shouldn't really matter.

If you insist, I'll keep the plugin name unchanged, but I'd still want to change at least internal and display names.

**Comment by OneMoreGres** [comment]
I'm still holding the point, that having equally (even not so precise) named entities is better then having a mess. Renaming plugin's name in json file or internal constants will lead to loss of user settings. Renaming file's name - to duplicate plugins after updating. Changing namespace/class names is acceptable, but i've told about it in the beginning.
And the main doubt is a reason of changes: i just don't see any real advantages here. Such renaming doesn't clarify anything or fix conflicts - it's just a matter of taste.

**Comment by orgads** [comment]
Actually what disturbed me were the display names. I care less for the file name _or_ the plugin name, but having a tab named "QtcCppcheck" in Analyzer is bad...

**Comment by OneMoreGres** [comment]
Well, that's acceptable. UI text does not impact on anything except translations. I'll change it.

**Pull request closed without merging**
